config/routes.rb
Social::Application.routes.draw do
  devise_for :users

  root 'home#index'

  # TODO: be sure only the needed routes are generated
  resources :posts

  resources :users do
    collection do
      post 'befriend'
    end
  end
  
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  # Gets user's friends' posts
  def self.feed_posts(user)
    find_by_sql("SELECT * FROM posts INNER JOIN friendships ON friendships.user_id = '#{user.id}' AND posts.author_id = friendships.friend_id ORDER BY created_at DESC")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Posts that have been made by this user
  has_many :authored_posts, -> { order(:created_at).includes(:author) }, class_name: "Post", foreign_key: "author_id"
  
  # Posts that have been posted by user's friends on the user's wall
  has_many :received_posts, -> { order(:created_at).includes(:author) }, class_name: "Post", foreign_key: "recipient_id"

  has_many :friendships
  has_many :friends, through: :friendships, source: :friend

  def is_friend_with?(user)
    friendships.where(:friend_id => user.id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :full_name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # Redirect logged in users to their feed
    if user_signed_in?
      redirect_to posts_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to :back, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  def index
    @posts = Post.feed_posts(current_user)
  end

  private
  def post_params
    params.require(:post).permit(:content, :recipient_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.order(:full_name)
  end

  def befriend
    friend = User.find(params[:friend_id])
    current_user.friendships.build(friend_id: friend.id)
    friend.friendships.build(friend_id: current_user.id)

    current_user.save!
    friend.save!

    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.slim
h1 Welcome to Social

p
  = link_to "Sign up", new_user_registration_path
  |  or 
  = link_to "sign in", new_user_session_path

app/views/layouts/application.slim
doctype html
html
  head
    title Social
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true 
    = csrf_meta_tags

body
  p.notice= notice
  p.alert= alert

  - if user_signed_in?
    = link_to "Feed", posts_path
    = " | "
    = link_to "My profile", current_user
    = " | "
    = link_to "Discover people", users_path

  = yield

app/views/posts/_form.slim
= form_for Post.new(:recipient_id => recipient_id) do |f|
  = f.hidden_field :recipient_id
  = f.text_field :content
  = f.submit "Post"

app/views/posts/_show.slim
hr
p
  span.username= link_to post.author.full_name, post.author
  span.post_content<= post.content
  br
  = time_ago_in_words(post.created_at) + " ago"

app/views/posts/index.slim
h1 Feed

- if @posts.empty?
  p 
    | Looks like your feed is empty.
    =< link_to "Get started by adding friends.", users_path

- for post in @posts
  = render partial: "posts/show", locals: { post: post }

app/views/users/index.slim
h1 Discover people

- for user in @users
  p= link_to user.full_name, user

app/views/users/show.slim
h1= @user.full_name
ul
  li= "Member since " + @user.created_at.to_date.to_s(:long)
  li= "Has #{pluralize(@user.friendships.count, 'friend')}"

/ Hide friendship stuff on user's own profile
- if current_user.id != @user.id

  - if current_user.is_friend_with?(@user)
    p= "You are friends with #{@user.full_name}!"
  - else
    = link_to "Befriend", befriend_users_path(friend_id: @user.id), method: "post"

- for post in @user.received_posts
  = render partial: "posts/show", locals: { post: post }

= render partial: "posts/form", locals: { recipient_id: @user.id }